### ISSUE TITLE
Basic questions

### ISSUE THREAD

**Issue by schmunk42** [omauger/docker-compose-php#2]
This is looking really great on first sight. I also implemented a `docker-compose` prototype a while ago, but that was rather a hack compared to what I see here.

I'd also have some questions and feedback...
- How do you configure `docker-compose` inside the PHP container? I had to use ENV vars like `DOCKER_HOST` for that.
- I used this nice library [php-shellcommand](https://github.com/mikehaertl/php-shellcommand) to execute commands, may be worth a look. But I haven't played around with your code.
- Just as an inspiration: https://github.com/francescou/docker-compose-ui
- Do you plan to actively develop this library?

**Comment by omauger** [comment]
Thanks for your questions, and sorry for the delay for my responses :
- Yes to configure docker server for your docker-compose command you need to set ENV vars. Do you think it's a good case to permit to configure this inside this library ?
- Thanks for php-shellcommand library, I think I will use it :)
- I know docker-compose-ui but I wanted a library to do docker-compose from php, and I think doing this in python too.
- Yes I plan to actively develop this library at least for work with new versions of docker and docker-compose because I use this library for my functional tests in php development. I will realy happy if you want use it to and even more if people want to contribute.

**Comment by schmunk42** [comment]
Thank you for the feedback, sounds great!

One more thing, just in case... I bet you're familiar with https://github.com/docker/libcompose - I haven't looked at the code very much, but I think it could be a good reference implementation for a library for compose.
